sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t nataliaferrazzo/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true nataliaferrazzo/docker-react npm run test

